language: android

sudo: false

cache:
  directories:
  - "$HOME/.gradle"

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - sys-img-armeabi-v7a-android-21
  - extra-android-m2repository

jdk:
- oraclejdk8

script:
- "./gradlew sherlock:testDebugUnitTest"